export const ADD_ARTICLE = "ADD_ARTICLE";
export const RESET_ARTICLES = "RESET_ARTICLES";
export const DELETE_ARTICLES = "DELETE_ARTICLES";
export const EDIT_ARTICLES = "EDIT_ARTICLES";
export const EDIT_ARTICLESPLUS = "EDIT_ARTICLESPLUS";